name: 'w3-action'
on:
  push:
    branches:
      - main

jobs:
  w3name-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: w3name publish
        uses: pawanpaudel93/w3name-action@v0.1
        with:
          cid: QmUT6WJJxHgPdk5HJNDAi1Vx86ftLH9RdjEyjMh1MQh8Bi
          signing_key: ${{  secrets.SIGNING_KEY }}
